"""empty message

Revision ID: 4484543aa1f1
Revises: 4c24d0ab29b4
Create Date: 2025-06-18 11:30:48.055243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4484543aa1f1'
down_revision: Union[str, None] = '4c24d0ab29b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('title', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'notes', ['title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notes', type_='unique')
    op.drop_column('notes', 'title')
    # ### end Alembic commands ###
