"""empty message

Revision ID: 9a0079a7a33d
Revises: d1ca4350e06b
Create Date: 2025-06-26 15:29:08.111329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a0079a7a33d'
down_revision: Union[str, None] = 'd1ca4350e06b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('notes', sa.Column('importance', sa.Integer(), nullable=True))
    op.add_column('notes', sa.Column('tags', sa.Text(), nullable=True))
    op.add_column('notes', sa.Column('summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'summary')
    op.drop_column('notes', 'tags')
    op.drop_column('notes', 'importance')
    op.drop_column('notes', 'category')
    # ### end Alembic commands ###
